name: publish splunk-otel-java docker image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: docker/setup-buildx-action@v2

      - name: Set the major version number
        run: echo MAJOR_VERSION=${GITHUB_REF_NAME} | sed -e 's/\..*//' >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: try echo
        run: echo ghcr.io/breedx-splk/ghcr-publish-exp/splunk-otel-instrumentation-java:${{ env.MAJOR_VERSION }}
      - name: try echo 2
        run: echo ghcr.io/breedx-splk/ghcr-publish-exp/splunk-otel-instrumentation-java:${GITHUB_REF_NAME}
      - name: try echo 3
        run: echo MAJOR_VERSION=${GITHUB_REF_NAME}

      - name: build and publish container
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          file: Dockerfile
          build-args: |
            RELEASE_VER=${ GITHUB_REF_NAME }
          tags: |
            ghcr.io/breedx-splk/ghcr-publish-exp/splunk-otel-instrumentation-java1:latest
            ghcr.io/breedx-splk/ghcr-publish-exp/splunk-otel-instrumentation-java2:${{env.MAJOR_VERSION}}
            ghcr.io/breedx-splk/ghcr-publish-exp/splunk-otel-instrumentation-java3:${GITHUB_REF_NAME}


